### ISSUE TITLE
vertically integrated moisture transport

### ISSUE THREAD

**Issue by nitesh1403** [jenfly/monsoon-onset#1]
How to do vertical integration, I did
uq_int = atm.int_pres(uq, pmin=300e2)

But error: module 'atmos' has no attribute 'int_pres'

**Comment by jenfly** [comment]
Hi @nitesh1403, sorry for the late reply! I thought I had archived this repository but apparently not. I'm no longer maintaining this repository so unfortunately I can't help with your issue. Best wishes!
